name: C++ Compile and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ environment
      run: sudo apt-get install -y g++

    - name: Compile the program
      run: g++ -o bank_account main.cpp BankAccount.cpp

    - name: Run the program
      run: ./bank_account
