name: C/C++ CI

on:
  push:
    branches: [ "new" ]
  pull_request:
    branches: [ "new" ]

jobs:
  build: g++ -o bank_account main.cpp BankAccount.cpp

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./bank_account
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
